version: '3.9'
# use postgres:13 image for the database
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: guest
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
    ports:
      - "5433:5432"
    volumes:
      - mysqldata:/var/lib/postgresql/data
    networks:
      - chat-engine-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - chat-engine-network

volumes:
  mysqldata:
  redis-data:

networks:
  chat-engine-network:
    driver: bridge
